# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 539)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_depth_acm_count = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.lbl_depth_acm_count.setFont(font)
        self.lbl_depth_acm_count.setObjectName("lbl_depth_acm_count")
        self.verticalLayout.addWidget(self.lbl_depth_acm_count)
        self.sbx_depth_acm_count = QtWidgets.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.sbx_depth_acm_count.setFont(font)
        self.sbx_depth_acm_count.setProperty("value", 20)
        self.sbx_depth_acm_count.setObjectName("sbx_depth_acm_count")
        self.verticalLayout.addWidget(self.sbx_depth_acm_count)
        self.lbl_outlier_remove_parameters = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.lbl_outlier_remove_parameters.setFont(font)
        self.lbl_outlier_remove_parameters.setObjectName("lbl_outlier_remove_parameters")
        self.verticalLayout.addWidget(self.lbl_outlier_remove_parameters)
        self.verticalFrame = QtWidgets.QFrame(Dialog)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.verticalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame.setLineWidth(1)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_iqr = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.lbl_iqr.setFont(font)
        self.lbl_iqr.setObjectName("lbl_iqr")
        self.verticalLayout_2.addWidget(self.lbl_iqr)
        self.gridFrame_iqr = QtWidgets.QFrame(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.gridFrame_iqr.setFont(font)
        self.gridFrame_iqr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gridFrame_iqr.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gridFrame_iqr.setObjectName("gridFrame_iqr")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame_iqr)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.sbx_iqr1 = QtWidgets.QSpinBox(self.gridFrame_iqr)
        self.sbx_iqr1.setProperty("value", 30)
        self.sbx_iqr1.setObjectName("sbx_iqr1")
        self.gridLayout.addWidget(self.sbx_iqr1, 0, 1, 1, 1)
        self.lbl_iqr3 = QtWidgets.QLabel(self.gridFrame_iqr)
        self.lbl_iqr3.setObjectName("lbl_iqr3")
        self.gridLayout.addWidget(self.lbl_iqr3, 1, 0, 1, 1)
        self.sbx_iqr3 = QtWidgets.QSpinBox(self.gridFrame_iqr)
        self.sbx_iqr3.setProperty("value", 70)
        self.sbx_iqr3.setObjectName("sbx_iqr3")
        self.gridLayout.addWidget(self.sbx_iqr3, 1, 1, 1, 1)
        self.lbl_iqr1 = QtWidgets.QLabel(self.gridFrame_iqr)
        self.lbl_iqr1.setObjectName("lbl_iqr1")
        self.gridLayout.addWidget(self.lbl_iqr1, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.gridFrame_iqr)
        self.lbl_gaussian = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.lbl_gaussian.setFont(font)
        self.lbl_gaussian.setObjectName("lbl_gaussian")
        self.verticalLayout_2.addWidget(self.lbl_gaussian)
        self.horizontalFrame = QtWidgets.QFrame(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.horizontalFrame.setFont(font)
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_gaussian_threshold = QtWidgets.QLabel(self.horizontalFrame)
        self.lbl_gaussian_threshold.setObjectName("lbl_gaussian_threshold")
        self.horizontalLayout.addWidget(self.lbl_gaussian_threshold)
        self.sbx_gaussian_threshold = QtWidgets.QDoubleSpinBox(self.horizontalFrame)
        self.sbx_gaussian_threshold.setSingleStep(0.1)
        self.sbx_gaussian_threshold.setProperty("value", 1.2)
        self.sbx_gaussian_threshold.setObjectName("sbx_gaussian_threshold")
        self.horizontalLayout.addWidget(self.sbx_gaussian_threshold)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.lbl_sor_filter = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.lbl_sor_filter.setFont(font)
        self.lbl_sor_filter.setObjectName("lbl_sor_filter")
        self.verticalLayout_2.addWidget(self.lbl_sor_filter)
        self.gridFrame_outlier = QtWidgets.QFrame(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.gridFrame_outlier.setFont(font)
        self.gridFrame_outlier.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gridFrame_outlier.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gridFrame_outlier.setObjectName("gridFrame_outlier")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_outlier)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sbx_nb_neighbors = QtWidgets.QSpinBox(self.gridFrame_outlier)
        self.sbx_nb_neighbors.setProperty("value", 20)
        self.sbx_nb_neighbors.setObjectName("sbx_nb_neighbors")
        self.gridLayout_2.addWidget(self.sbx_nb_neighbors, 0, 1, 1, 1)
        self.lbl_nb_neighbors = QtWidgets.QLabel(self.gridFrame_outlier)
        self.lbl_nb_neighbors.setObjectName("lbl_nb_neighbors")
        self.gridLayout_2.addWidget(self.lbl_nb_neighbors, 0, 0, 1, 1)
        self.lbl_std_ratio = QtWidgets.QLabel(self.gridFrame_outlier)
        self.lbl_std_ratio.setObjectName("lbl_std_ratio")
        self.gridLayout_2.addWidget(self.lbl_std_ratio, 1, 0, 1, 1)
        self.sbx_std_ratio = QtWidgets.QDoubleSpinBox(self.gridFrame_outlier)
        self.sbx_std_ratio.setSingleStep(0.1)
        self.sbx_std_ratio.setProperty("value", 2.0)
        self.sbx_std_ratio.setObjectName("sbx_std_ratio")
        self.gridLayout_2.addWidget(self.sbx_std_ratio, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gridFrame_outlier)
        self.verticalLayout.addWidget(self.verticalFrame)
        self.lbl_icp_parameters = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.lbl_icp_parameters.setFont(font)
        self.lbl_icp_parameters.setObjectName("lbl_icp_parameters")
        self.verticalLayout.addWidget(self.lbl_icp_parameters)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridFrame_icp = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setFamily("현대하모니 L")
        font.setPointSize(10)
        self.gridFrame_icp.setFont(font)
        self.gridFrame_icp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.gridFrame_icp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridFrame_icp.setObjectName("gridFrame_icp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_icp)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_loss_sigma = QtWidgets.QLabel(self.gridFrame_icp)
        self.lbl_loss_sigma.setObjectName("lbl_loss_sigma")
        self.gridLayout_3.addWidget(self.lbl_loss_sigma, 1, 0, 1, 1)
        self.lbl_icp_threshold = QtWidgets.QLabel(self.gridFrame_icp)
        self.lbl_icp_threshold.setObjectName("lbl_icp_threshold")
        self.gridLayout_3.addWidget(self.lbl_icp_threshold, 0, 0, 1, 1)
        self.lbl_icp_iteration = QtWidgets.QLabel(self.gridFrame_icp)
        self.lbl_icp_iteration.setObjectName("lbl_icp_iteration")
        self.gridLayout_3.addWidget(self.lbl_icp_iteration, 2, 0, 1, 1)
        self.sbx_icp_iteration = QtWidgets.QSpinBox(self.gridFrame_icp)
        self.sbx_icp_iteration.setProperty("value", 10)
        self.sbx_icp_iteration.setObjectName("sbx_icp_iteration")
        self.gridLayout_3.addWidget(self.sbx_icp_iteration, 2, 1, 1, 1)
        self.sbx_icp_threshold = QtWidgets.QDoubleSpinBox(self.gridFrame_icp)
        self.sbx_icp_threshold.setSingleStep(0.1)
        self.sbx_icp_threshold.setProperty("value", 0.02)
        self.sbx_icp_threshold.setObjectName("sbx_icp_threshold")
        self.gridLayout_3.addWidget(self.sbx_icp_threshold, 0, 1, 1, 1)
        self.sbx_loss_sigma = QtWidgets.QDoubleSpinBox(self.gridFrame_icp)
        self.sbx_loss_sigma.setSingleStep(0.1)
        self.sbx_loss_sigma.setProperty("value", 0.05)
        self.sbx_loss_sigma.setObjectName("sbx_loss_sigma")
        self.gridLayout_3.addWidget(self.sbx_loss_sigma, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.gridFrame_icp)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_depth_acm_count.setText(_translate("Dialog", "■ Depth 누적 횟수"))
        self.lbl_outlier_remove_parameters.setText(_translate("Dialog", "■ Outlier 제거 파라미터"))
        self.lbl_iqr.setText(_translate("Dialog", "1. IQR (Inter Quatile Range) 기반 아웃라이어 제거"))
        self.lbl_iqr3.setText(_translate("Dialog", "IQR3"))
        self.lbl_iqr1.setText(_translate("Dialog", "IQR1"))
        self.lbl_gaussian.setText(_translate("Dialog", "2. 가우시안(Gaussian) 통계 기반 아웃라이어 제거 \n"
"   (데이터 포인트가 가우시안 분포의 평균에서 Threshold 배 이상 떨어져 있다면 그것을 \n"
"   아웃라이어로 간주하고 이를 제거)"))
        self.lbl_gaussian_threshold.setText(_translate("Dialog", "Threshold"))
        self.lbl_sor_filter.setText(_translate("Dialog", "3. SOR Filter (Statistical Outlier Remove Filter)"))
        self.lbl_nb_neighbors.setText(_translate("Dialog", "nb_neighbors (Number of neighbors around the target point.)"))
        self.lbl_std_ratio.setText(_translate("Dialog", "std_ratio (Standard deviation ratio.)"))
        self.lbl_icp_parameters.setText(_translate("Dialog", "■ ICP 파라미터"))
        self.lbl_loss_sigma.setText(_translate("Dialog", "Loss sigma"))
        self.lbl_icp_threshold.setText(_translate("Dialog", "ICP Threshold"))
        self.lbl_icp_iteration.setText(_translate("Dialog", "ICP 반복 횟수"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

